name: Build & Deploy to Scaleway

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: navigate
      run: cd SQLizer-back
    - name: git
      run: git pull
    - name: docker kill
      run: docker compose down
    - name: docker run
      run: docker compose up -d