name: Build & Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: test
      run: cd SQLizer-back && git pull && docker compose down && docker compose up -d